name: Run Docs Scraper 1400

on:
  schedule:
  - cron: "0 07 * * *"
  
jobs:
  cron:
    runs-on: ubuntu-20.04
    name: scraping docs
    steps:
      - uses: actions/checkout@v4
      - name: Run scraper
        env:
          HOST_URL: https://meilsearch.whatap.io
          API_KEY: dgoMBc2t6fVzILDGqhh63uBXACGOmJbKNnE_Xv8_Hqk
          CONFIG_FILE_PATH: ${{ github.workspace }}/whatap-docs.json
        run: |
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$HOST_URL \
            -e MEILISEARCH_API_KEY=$API_KEY \
            -v $CONFIG_FILE_PATH:/docs-scraper/config.json \
            getmeili/docs-scraper:v0.12.11 pipenv run ./docs_scraper config.json
      - name: Swap index
        env:
          API_KEY: dgoMBc2t6fVzILDGqhh63uBXACGOmJbKNnE_Xv8_Hqk
        run: |
          curl \
            -X POST 'https://meilsearch.whatap.io/swap-indexes' \
            -H "Authorization: Bearer $API_KEY" \
            -H 'Content-Type: application/json' \
            --data-binary '[ { "indexes": [ "whatap-temp", "whatap" ] } ]'